Hw7
FlameHost10/Tinkoff_Backend_2023-2024 pull request #3
Opened 2023-11-26 13:40 UTC by FlameHost10

2023-12-04 16:07 UTC, snitron requested changes
Нужно исправить задачи. С учётом того, что не выполнено задание 4, максимум смогу поставить 2 балла при успешных доработках

2023-12-15 17:42 UTC, FlameHost10 commented
Здравствуйте, я закончила последние правки в коде, на которые вы указали. 

PS. прошу прощение за то, что так поздно отправляю. Я улетала по семейным обстоятельствам в другой город, где не могла работать.

2023-12-15 17:53 UTC, FlameHost10 commented
И ещё хотела спросить, я обнаружила, что у меня уже очень давно висит не проверенное дз 6. Может оно затерялось в потоке домашек

2023-12-17 00:01 UTC, snitron approved these changes
Баллы поставил
2/3

2023-12-17 00:02 UTC, snitron commented
Домашки не затерялись, посмотрю ASAP!

PS: если делаешь исправления, пж отправляй на проверку в платформе заново, а то не видно, что нужно проверить

2024-01-09 17:26 UTC, merged